channels:
  - conda-forge
dependencies:
  - r-base=4.3.3
  - r-irkernel
  - r-tidyverse
  - r-ragg
  - r-xlsx
  - r-readxl
  - r-haven
  - r-remotes
  - r-devtools
  - r-pacman
  - r-naniar
  - r-fastdummies
  - r-rmarkdown
  - r-quarto
  - r-formatr
  - r-summarytools
  - r-gtextras
  - r-kableextra
  - r-tinytex
  - r-estimatr
  - r-modelsummary
  - r-marginaleffects
  - r-gt
  - r-ggExtra
  - r-sf
  - r-raster
  - r-terra
