#!/usr/bin/env -S bash -v

quarto install tinytex

echo Run setup.R
Rscript setup.R

# RStudio設定の移植
mkdir -p ~/.config/rstudio
mv rstudio-prefs.json ~/.config/rstudio/rstudio-prefs.json

rm apt.txt README.md environment.yml postBuild setup.R
